name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  deploy-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd infra/environment
          terraform init
          terraform apply -auto-approve -var-file ./prod.tfvars
        name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g lerna
      - run: npm ci
      - run: lerna bootstrap
      - run: lerna run build
        name: Build
      - run: lerna run test
        name: Test
      - run: lerna run gen-avro
        name: Generate Avro
      - name: Upload member service artifacts
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: |
            services/**/dist
            services/**/infra
            services/**/avro
            services/**/package.json
            services/**/package-lock.json
            services/**/tsconfig.json
            services/**/*.ispec.ts
            node_modules
            infra/*


  deploy-member-service:
    needs: [build, deploy-global]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: src
      - run: |
          cd services/members/members-service/infra
          terraform init
          terraform apply -auto-approve -var-file ./prod.tfvars
        name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  members-service-acceptance-test:
    needs: [deploy-member-service]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: src
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run itest
        name: Acceptance Test
        working-directory: services/members/members-service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
